version: '3.7'
services:
  nodejs:
    build: .
    container_name: nodejs
    volumes:
      - ./:/app
    restart: always
    ports:
      - 3001:3001
    tty: true
    stdin_open: true
    networks:
      - nodejs

volumes:
  db-data:
    external: false

networks:
  nodejs:
